stages:
  - build

image: docker:latest

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2
  RUST_VERSION: stable

services:
  - name: docker:dind
    alias: localhost

before_script:
  - apk add --no-cache curl build-base libgcc bash
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  - source $HOME/.cargo/env
  - rustup override set $RUST_VERSION
  - cargo install cross --git https://github.com/cross-rs/cross

build_android:
  stage: build
  script:
    - chmod +x ./mobile/android/build.sh
    - /bin/bash ./mobile/android/build.sh
  variables:
    CROSS_CONTAINER_IN_CONTAINER: "true"
  artifacts:
    paths:
      - ./mobile/android/out/
