[package]
name = "simple-c2pa"
version = "0.0.10"
edition = "2021"

[dependencies]
c2pa = { version = "0.28.3", features = ["file_io", "add_thumbnails"] }
log = "0.4.20"
openssl = "0.10.48"
ring = "0.17.5"
serde = "1.0.192"
serde_json = "1.0.108"
tempfile = "3.8.1"
thiserror = "1.0.50"
uniffi = { version = "0.25.2", features = ["build", "cli"] }

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[lib]
name = "simple_c2pa"
crate-type = ["lib", "staticlib", "cdylib"]

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"
