stages:
  - build
  - upload
  - release

build_android:
  only:
    - main
    - develop
    - tags
  tags:
    - proofmode-debian
  stage: build
  script:
    - cargo make android-build
  artifacts:
    paths:
      - ./out/android/

publish_android:
  image: mobiledevops/android-sdk-image:33.0.2
  only:
    - tags
  stage: release
  script:
    - cp -r out/android/* android/project/simple_c2pa/src/main/
    - ls -al android/project/simple_c2pa/src/main/
    - cd android/project && ./gradlew clean assembleRelease && ./gradlew publish
