stages:
  - build

.macos_runners:
  tags:
    - proofmode-macos
  before_script:
    - echo "started by ${GITLAB_USER_NAME}"

build_apple:
  extends:
    - .macos_runners
  stage: build
  script:
    - ./mobile/apple/build.sh
  artifacts:
    paths:
      - ./mobile/apple/out/
