stages:
  - build
  - release

.macos_runners:
  tags:
    - proofmode-macos
  before_script:
    - echo "started by ${GITLAB_USER_NAME}"

build_apple:
  extends:
    - .macos_runners
  stage: build
  script:
    - ./mobile/apple/build.sh
  artifacts:
    paths:
      - ./mobile/apple/out/

release_apple:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "running release_apple for $TAG"
  release:
    tag_name: "v0.$CI_PIPELINE_IID"
    description: "v0.$CI_PIPELINE_IID"
    ref: "$CI_COMMIT_SHA"
    assets:
      links:
        - name: "simple_c2pa_mobile.swift"
          url: "https://gitlab.com/guardianproject/proofmode/simple-c2pa/-/jobs/$JOB_ID/artifacts/download"
        - name: "simple_c2pa_mobile.xcframework.zip"
          url: "https://gitlab.com/guardianproject/proofmode/simple-c2pa/-/jobs/$JOB_ID/artifacts/download"
